### ISSUE TITLE
Add option to use mousehweel / page scrolling

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/Alternate-Method-Editor#1] opened 2019-03-19 08:48 UTC
Hi,
when I open a Method, it´s right no not possible to scroll down using the mousewheel.
This one seems to be a known issue in the monaco editor. There seem to be a solution available, but haven´t tested yet.
https://github.com/Microsoft/monaco-editor/issues/69

**Comment by AngelaIp** [comment] 2019-03-19 12:53
Short update: In my test db page scrolling worked for Chrome, but not for Firefox 60.3.0esr. Maybe a browser related issue.

**Comment by cgillis-aras** [comment] 2019-03-26 14:23
Hi @AngelaIp,
I can confirm that scrolling works for me in both Chrome and Edge, and that it does not seem to be working in Firefox. I looked through the editor file, and it appears that the fix you referenced has already been implemented in the version of the Monaco Editor that I'm using in this project.

I'll do some more investigation to see if I can figure out what the issue with Firefox is.

**Comment by cgillis-aras** [comment] 2019-03-26 14:25
Looks like there's an issue filed on the Monaco Editor repository about mouse-wheel scrolling not working in Firefox. https://github.com/Microsoft/monaco-editor/issues/1353

**Comment by cgillis-aras** [comment] 2019-03-26 14:59
Fixed in 9d32c575daf03fa5c90d255e3826fd92a8f7b7cc

**Closed as completed by cgillis-aras** 2019-03-26 14:59 UTC
Labels: Type: Bug, Help Wanted
